# Generated by Django 3.1 on 2021-05-14 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
